title: A Round Cover to the Square Manhole
author: LeDuke-AS
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  A good start, this sure is. A practice run for now. Who knows what might happen next.

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
